"""Select arm E's architecture. Pre-registration §6. Run ONCE, before any training.

Storage depends only on architecture under the §7 fixed-width convention, so this is fully
determined before a single weight is trained and is never revisited. The result is written
to src/arm_e_constants.py and committed; run manifests read it from there.
"""

import argparse
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from src import storage
from src.models import ARM_E_CANDIDATES, resnet6n2, resnet18_cifar

OUT_PY = pathlib.Path(__file__).resolve().parents[1] / "src" / "arm_e_constants.py"
TIE_BREAK_BAND = 0.05


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="write src/arm_e_constants.py")
    args = ap.parse_args()

    r18 = resnet18_cifar()
    ternary_names = storage.ternarizable_conv_names(r18)
    target = storage.ternary_storage_bits(r18, ternary_names)

    rows = []
    for depth, n in ARM_E_CANDIDATES.items():
        model = resnet6n2(n)
        bits = storage.fp32_storage_bits(model)
        rows.append(
            {
                "depth": depth,
                "n": n,
                "parameters": storage.n_parameters(model),
                "storage_bits": bits,
                "storage_mb": storage.mb(bits),
                "rel_error": abs(bits - target) / target,
            }
        )

    best = min(rows, key=lambda r: r["rel_error"])
    # "Ties resolve to the smaller network when the relative errors differ by less than 5%"
    # (§6) -- read as: candidates whose rel_error is within 0.05 of the minimum are tied.
    band = [r for r in rows if abs(r["rel_error"] - best["rel_error"]) < TIE_BREAK_BAND]
    chosen = min(band, key=lambda r: r["parameters"])

    print(f"ternary ResNet-18 target : {target:,} bits = {storage.mb(target):.4f} MB")
    print(f"{'depth':>6} {'params':>10} {'bits':>14} {'MB':>9} {'|d|/target':>11}")
    for r in sorted(rows, key=lambda r: r["depth"]):
        mark = " <-- selected" if r["depth"] == chosen["depth"] else ""
        print(
            f"{r['depth']:>6} {r['parameters']:>10,} {r['storage_bits']:>14,} "
            f"{r['storage_mb']:>9.4f} {r['rel_error']:>11.4f}{mark}"
        )
    print(f"\ntie-break band (within {TIE_BREAK_BAND:.0%} of best): "
          f"{[r['depth'] for r in band]}")
    print(f"selected: ResNet-{chosen['depth']}")

    if args.write:
        OUT_PY.write_text(
            '"""GENERATED by scripts/select_arm_e.py -- do not edit.\n\n'
            "Arm E's architecture and the two storage figures of prereg §6, fixed before\n"
            'training and never revisited.\n"""\n\n'
            f"ARM_E_DEPTH = {chosen['depth']}\n"
            f"ARM_E_N = {chosen['n']}\n"
            f"ARM_E_PARAMETERS = {chosen['parameters']}\n"
            f"ARM_E_STORAGE_BITS = {chosen['storage_bits']}\n"
            f"TERNARY_R18_STORAGE_BITS = {target}\n"
            f"SELECTION_TABLE = {json.dumps(rows, indent=4)}\n",
            encoding="utf-8",
        )
        print(f"wrote {OUT_PY}")


if __name__ == "__main__":
    main()
