"""Single-run training loop. Pre-registration sections 5 and 11; amendment A3.

This module never imports or instantiates the test loader. Validation is evaluated every
epoch for learning curves, the settledness criterion and the teacher gate -- never for
checkpoint selection.
"""

import json
import pathlib
import platform
import random
import socket
import subprocess
import time

import numpy as np
import torch
import torch.nn.functional as F

from src.data import SPLIT_SEED, train_val_loaders
from src.losses import LAMBDA, T_DEFAULT, kd_loss
from src.models import EXPECTED_TERNARY_CONVS, resnet6n2, resnet18_cifar, resnet34_cifar
from src.ternary_modules import TernaryConv2d, ternarize_model
from src.tracking import TernaryTracker

EPOCHS = 160
LR = 0.1
MILESTONES = (80, 120)  # LR drops BEFORE these 1-indexed epochs begin
GAMMA = 0.1
BATCH_SIZE = 128
MOMENTUM = 0.9  # plain, NOT Nesterov
WEIGHT_DECAY = 1e-4
CLAMP = (-1.0, 1.0)
CHECKPOINT_EPOCHS = range(151, 161)

ARM_SPEC = {
    "T": {"arch": "resnet34_cifar", "ternary": False, "kd": False},
    "A": {"arch": "resnet18_cifar", "ternary": False, "kd": False},
    "B": {"arch": "resnet18_cifar", "ternary": False, "kd": True},
    "C": {"arch": "resnet18_cifar", "ternary": True, "kd": False},
    "D": {"arch": "resnet18_cifar", "ternary": True, "kd": True},
    "E": {"arch": "resnet6n2", "ternary": False, "kd": False},
}

TEACHER_RUN = "T_0"
TEACHER_EPOCH = 160  # the final teacher: the one artifact training actually produces


def lr_for_epoch(epoch):
    """1-indexed: 0.1 for epochs 1-79, 0.01 for 80-119, 0.001 for 120-160.

    Computed directly rather than via MultiStepLR. With milestones (80, 120) and step()
    called once per epoch, MultiStepLR drops at epochs 81 and 121 -- an off-by-one that
    would shift every number in the study.
    """
    lr = LR
    for milestone in MILESTONES:
        if epoch >= milestone:
            lr *= GAMMA
    return lr


def param_groups(model):
    """Weight decay on conv and FC weights only; never on BatchNorm gamma/beta or biases.

    BN parameters and every bias are 1-D, conv weights are 4-D and the FC weight 2-D, so
    dimensionality separates them exactly.
    """
    decay, no_decay = [], []
    for param in model.parameters():
        if not param.requires_grad:
            continue
        (no_decay if param.ndim == 1 else decay).append(param)
    return [
        {"params": decay, "weight_decay": WEIGHT_DECAY},
        {"params": no_decay, "weight_decay": 0.0},
    ]


def set_determinism(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    # fp32 only: TF32 would silently drop convolution precision on Ampere and later.
    torch.backends.cuda.matmul.allow_tf32 = False
    torch.backends.cudnn.allow_tf32 = False


def build_model(arm, device):
    arch = ARM_SPEC[arm]["arch"]
    if arch == "resnet18_cifar":
        model = resnet18_cifar()
    elif arch == "resnet34_cifar":
        model = resnet34_cifar()
    elif arch == "resnet6n2":
        from src.arm_e_constants import ARM_E_N  # generated by scripts/select_arm_e.py

        model = resnet6n2(ARM_E_N)
    else:
        raise ValueError(arch)

    ternary_names = []
    if ARM_SPEC[arm]["ternary"]:
        ternary_names = ternarize_model(
            model, expected_count=EXPECTED_TERNARY_CONVS.get(arch)
        )
    return model.to(device), ternary_names


def load_teacher(runs_dir, device):
    path = pathlib.Path(runs_dir) / TEACHER_RUN / "checkpoints" / f"epoch_{TEACHER_EPOCH}.pt"
    if not path.exists():
        raise FileNotFoundError(f"teacher checkpoint missing: {path}. Train arm T first.")
    teacher = resnet34_cifar().to(device)
    teacher.load_state_dict(torch.load(path, map_location=device)["model"])
    teacher.eval()
    for param in teacher.parameters():
        param.requires_grad_(False)
    return teacher


@torch.no_grad()
def accuracy(model, loader, device):
    model.eval()
    correct = total = 0
    for inputs, targets in loader:
        inputs, targets = inputs.to(device), targets.to(device)
        correct += int((model(inputs).argmax(dim=1) == targets).sum())
        total += targets.numel()
    return 100.0 * correct / total


def clamp_latent(model):
    for module in model.modules():
        if isinstance(module, TernaryConv2d):
            module.weight.data.clamp_(*CLAMP)


def _git_commit():
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            cwd=pathlib.Path(__file__).resolve().parents[1],
        ).stdout.strip()
    except Exception:
        return "unknown"


def _rng_state():
    return {
        "python": random.getstate(),
        "numpy": np.random.get_state(),
        "torch": torch.get_rng_state(),
        "cuda": torch.cuda.get_rng_state_all() if torch.cuda.is_available() else [],
    }


def _restore_rng(state):
    random.setstate(state["python"])
    np.random.set_state(state["numpy"])
    torch.set_rng_state(state["torch"])
    if state["cuda"] and torch.cuda.is_available():
        torch.cuda.set_rng_state_all(state["cuda"])


def _truncate_metrics(path, last_epoch):
    """Drop metrics lines past the resume point, so a crash between appending a line and
    writing resume.pt cannot duplicate an epoch."""
    if not path.exists():
        return
    kept = [
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and json.loads(line)["epoch"] <= last_epoch
    ]
    path.write_text("".join(line + "\n" for line in kept), encoding="utf-8")


def is_complete(runs_dir, label):
    """True if this run already reached epoch 160 and wrote its manifest verdict."""
    manifest_path = pathlib.Path(runs_dir) / label / "manifest.json"
    if not manifest_path.exists():
        return False
    status = json.loads(manifest_path.read_text(encoding="utf-8")).get("discard_status")
    return status is not None and status != "running"


def run(arm, seed, runs_dir, data_dir, temperature=T_DEFAULT, label=None, device=None):
    """Train one run to completion and return its manifest.

    `label` names the run directory and defaults to f"{arm}_{seed}". It is overridden for
    the temperature sweep, whose points reuse arm D and its seeds.
    """
    spec = ARM_SPEC[arm]
    label = label or f"{arm}_{seed}"
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")

    run_dir = pathlib.Path(runs_dir) / label
    ckpt_dir = run_dir / "checkpoints"
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    metrics_path = run_dir / "metrics.jsonl"
    manifest_path = run_dir / "manifest.json"
    resume_path = run_dir / "resume.pt"

    set_determinism(seed)
    model, ternary_names = build_model(arm, device)
    optimizer = torch.optim.SGD(param_groups(model), lr=LR, momentum=MOMENTUM, nesterov=False)
    tracker = TernaryTracker(ternary_names) if ternary_names else None
    teacher = load_teacher(runs_dir, device) if spec["kd"] else None
    train_loader, val_loader = train_val_loaders(seed, root=data_dir, batch_size=BATCH_SIZE)

    manifest = {
        "arm": arm,
        "seed": seed,
        "label": label,
        "split_seed": SPLIT_SEED,
        "git_commit": _git_commit(),
        "hostname": socket.gethostname(),
        "gpu_model": torch.cuda.get_device_name(0) if torch.cuda.is_available() else "cpu",
        "torch_version": torch.__version__,
        "cuda_version": torch.version.cuda,
        "python_version": platform.python_version(),
        "start_time": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "end_time": None,
        "hyperparameters": {
            "epochs": EPOCHS,
            "lr": LR,
            "milestones": list(MILESTONES),
            "gamma": GAMMA,
            "batch_size": BATCH_SIZE,
            "momentum": MOMENTUM,
            "nesterov": False,
            "weight_decay": WEIGHT_DECAY,
            "T": temperature if spec["kd"] else None,
            "lambda": LAMBDA if spec["kd"] else None,
            "clamp": list(CLAMP) if ternary_names else None,
            "ste": "identity" if ternary_names else None,
        },
        "architecture": spec["arch"],
        "ternarized_layer_names": ternary_names,
        "teacher_run": TEACHER_RUN if spec["kd"] else None,
        "teacher_epoch": TEACHER_EPOCH if spec["kd"] else None,
        "discard_status": "running",
    }

    start_epoch = 1
    epoch1_loss = None
    if resume_path.exists():
        state = torch.load(resume_path, map_location=device, weights_only=False)
        model.load_state_dict(state["model"])
        optimizer.load_state_dict(state["optimizer"])
        if tracker is not None:
            tracker.load_state_dict(state["tracker"])
        _restore_rng(state["rng"])
        start_epoch = state["epoch"] + 1
        epoch1_loss = state["epoch1_loss"]
        _truncate_metrics(metrics_path, state["epoch"])
        print(f"[{label}] resuming at epoch {start_epoch}")
    else:
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    for epoch in range(start_epoch, EPOCHS + 1):
        epoch_lr = lr_for_epoch(epoch)
        for group in optimizer.param_groups:
            group["lr"] = epoch_lr

        model.train()
        started = time.time()
        step_losses = []
        for inputs, targets in train_loader:
            inputs = inputs.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)

            logits = model(inputs)  # quantization happens inside TernaryConv2d.forward
            if teacher is not None:
                with torch.no_grad():
                    teacher_logits = teacher(inputs)  # same augmented batch, computed online
                loss = kd_loss(logits, teacher_logits, targets, T=temperature)
            else:
                loss = F.cross_entropy(logits, targets)

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()
            if ternary_names:
                clamp_latent(model)  # after the update, per the fixed per-step order
            step_losses.append(loss.detach())

        step_losses = torch.stack(step_losses)
        # One finiteness check per epoch instead of per step: same coverage, and no host
        # sync inside the inner loop.
        if not torch.isfinite(step_losses).all():
            manifest["discard_status"] = "discarded:nan_or_inf_loss"
            manifest["end_time"] = time.strftime("%Y-%m-%dT%H:%M:%S")
            manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
            print(f"[{label}] DISCARD: non-finite loss at epoch {epoch}")
            return manifest

        loss_mean = float(step_losses.mean())
        if epoch == 1:
            epoch1_loss = loss_mean
        val_accuracy = accuracy(model, val_loader, device)

        record = {
            "epoch": epoch,
            "lr": epoch_lr,
            "train_loss_mean": loss_mean,
            "train_loss_final_step": float(step_losses[-1]),
            "val_accuracy": val_accuracy,
            "epoch_wall_time": time.time() - started,
        }
        if tracker is not None:
            per_layer, aggregate = tracker.update(model)
            record["per_layer"] = per_layer
            record["aggregate_reversal_rate"] = aggregate

        with metrics_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(record) + "\n")

        if epoch in CHECKPOINT_EPOCHS:
            torch.save(
                {"model": model.state_dict(), "epoch": epoch},
                ckpt_dir / f"epoch_{epoch}.pt",
            )

        torch.save(
            {
                "model": model.state_dict(),
                "optimizer": optimizer.state_dict(),
                "tracker": tracker.state_dict() if tracker is not None else None,
                "rng": _rng_state(),
                "epoch": epoch,
                "epoch1_loss": epoch1_loss,
            },
            resume_path,
        )

        if epoch == start_epoch:
            seconds = record["epoch_wall_time"]
            print(
                f"[{label}] {seconds:.1f}s/epoch measured -> "
                f"~{seconds * (EPOCHS - epoch) / 3600:.2f}h remaining on this run"
            )
        print(
            f"[{label}] epoch {epoch}/{EPOCHS} lr={epoch_lr:g} "
            f"loss={loss_mean:.4f} val={val_accuracy:.2f}%"
        )

    # Discard criterion 2: the run did not learn at all over its whole length.
    last_record = json.loads(metrics_path.read_text(encoding="utf-8").splitlines()[-1])
    if last_record["train_loss_mean"] > epoch1_loss:
        manifest["discard_status"] = "discarded:loss_did_not_decrease"
        print(
            f"[{label}] DISCARD: epoch 160 loss {last_record['train_loss_mean']:.4f} "
            f"exceeds epoch 1 loss {epoch1_loss:.4f}"
        )
    else:
        manifest["discard_status"] = "completed"

    manifest["end_time"] = time.strftime("%Y-%m-%dT%H:%M:%S")
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest
